spring:
  security:
    filter-order: 3
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.ProgressDialect
  datasource_docker:
    url: jdbc:postgresql://localhost:5433/mulakat
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  datasource:
    url: jdbc:postgresql://ec2-52-70-205-234.compute-1.amazonaws.com:5432/d9a47nqkfdc8m3
    username: iyvvzmktuweomi
    password: 2bbd7a1b514d84aba31d58de765dcdbb9c22b1304cc3a85aa4027b46aefb93b3
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  datasource_cloud:
    url: jdbc:postgresql://castor.db.elephantsql.com:5432/fqiwnyit
    username: fqiwnyit
    password: 4zaCiiSIS46dENWrCPfHHZcS20QDKHsp
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  liquibase:
    change-log: classpath:db/db-init.xml
    contexts: ${_CONTEXT:prod,test,init}
security:
  filter-order: 3